### ISSUE TITLE
Add instrumentation for net/http and net/httptrace

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go-contrib#158]
See https://github.com/open-telemetry/opentelemetry-go/issues/974.

# Tasks

- [x]  code complete with tests passing
- [x]  Dockerfile with example app showing instrumentation
- [x]  documentation updated
- [x]  instrumentation added to the opentelemetry registry

**Comment by MrAlias** [comment]
I think this might be complete.
