### ISSUE TITLE
Unify instrumentation *Provider options

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#213]
Currently there are many instrumentation packages that are directly configurable with a `Tracer` or `Meter` to use in the telemetry they gather.

- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/32a76fe5fd2bafc439463d61320152a2987cc881/instrumentation/go.mongodb.org/mongo-driver/config.go#L50
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/370078e3876afd8713a3e25076fe1e71f1f21587/instrumentation/github.com/gin-gonic/gin/option.go#L36
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/370078e3876afd8713a3e25076fe1e71f1f21587/instrumentation/github.com/gorilla/mux/config.go#L35
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/370078e3876afd8713a3e25076fe1e71f1f21587/instrumentation/github.com/labstack/echo/config.go#L35
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/19be05c53f11474ac0d1bf248b4a48a4c75100e0/instrumentation/github.com/emicklei/go-restful/config.go#L35
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/70957fc44e1fe809e2b961a43eeea390fa247038/instrumentation/github.com/Shopify/sarama/option.go#L55
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7066c0829eab0b7992fe4b9f2ada1d8949d7c874/instrumentation/github.com/gocql/gocql/config.go#L84
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/3fc65dc78f63bed02e186a9c22b7eb32b565fc56/instrumentation/net/http/config.go#L62
- https://github.com/open-telemetry/opentelemetry-go-contrib/blob/3fc65dc78f63bed02e186a9c22b7eb32b565fc56/instrumentation/net/http/config.go#L70

They should not be configurable to do this. It is the instrumentations job to define the `Tracer` or `Meter` they use from a `*Provider`.

The [`global`](https://github.com/open-telemetry/opentelemetry-go/tree/master/api/global) package was made to provide this  functionality. It provides a shim until an SDK is registered that will make sure all instrumentation use the correct `*Provider`s. However, since these instrumentation packages are expected to be wrapped in other instrumentation that might want the functionality to use a unique `*Provider` and the possible aversion some uses will have with the idea of globals, the instrumentation needs to be configurable to accept `*Provider`s instead of `Tracer`s and `Meter`s directly.

### TODO

- [ ] Remove all configuration for `Tracer` and `Meter` in the existing instrumentation.
- [ ] Refactor instrumentation to accept a `TraceProvider` if it uses a `Tracer`, a `MeterProvider` if it uses a `Meter`, and `Propagators` if it handles any context propagation. The default for each of these needs to be the one provided by the `global` package.
- [ ] Update the [instrumentation guidelines](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/instrumentation/README.md) to include this info.

_Originally posted by @XSAM in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/209#issuecomment-673236745_

**Comment by MrAlias** [comment]
Optionally, the instrumentation could be configured to accept a `*Provider` instead that would override the `global` package. As well maybe the configuration of `Propagators` could remain as well.

These could be useful to an operator if they wanted to separate out functionality. Though, outside of the propagators, I'm not immediately sure why.

**Comment by MrAlias** [comment]
From the SIG meeting today, instrumentation in this repo ...

1. MUST provide an option to accept a `TraceProvider` if it uses a `Tracer`, a `MeterProvider` if it uses a `Meter`, and `Propagators` if it handles any context propagation
2. MUST use the default `TraceProvider`, `MeterProvider`, and `Propagators` supplied by the `global` package if no optional one is provided.
3. MUST not provide an option to accept a `Tracer` or `Meter`.
4. MUST create any used `Tracer` or `Meter` with a name matching the instrumentation package name.

**Comment by XSAM** [comment]
I'd like to take this up.

**Comment by reggiemcdonald** [comment]
@XSAM yesterday I started a fix for the gocql instrumentation. Did you mind skipping that one?

**Comment by XSAM** [comment]
@reggiemcdonald Not at all, I will skip that part.

**Comment by XSAM** [comment]
@MrAlias 

> Refactor instrumentation to accept a TraceProvider if it uses a Tracer, a MeterProvider if it uses a Meter, and Propagators if it handles any context propagation. The default for each of these needs to be the one provided by the global package.

Maybe we can use `TracerProvider` instead of `TraceProvider`, because it brings more consistency for naming since the other provider is called `MeterProvider`.
