### ISSUE TITLE
comments for `otelgrpc/filters.HealthCheck` is incorrect

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry-go-contrib#2674]
## Background

**Package Link**: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/filters

gRPC filters are merged in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2572, but the comments for `filters.HealthCheck` is not updated correctly as mentioned https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2672#pullrequestreview-1074799969.

### Why can this instrumentation not be included in the package itself?

N/A

### Why can this instrumentation not be hosted in a dedicated repository?

N/A

## Proposed Solution

Update commments

### Tracing

N/A

### Metrics

N/A

### Prior Art

N/A

## Tasks

- Code complete:
  - [X] Comprehensive unit tests.
  - [X] End-to-end integration tests.
  - [X] Tests all passing.
  - [X] Instrumentation functionality verified.
- Documented
  - [X] Added to the [OpenTelemetry Registry](https://opentelemetry.io/registry/)
  - [X] README included for the module describing high-level purpose.
  - [X] Complete documentation of all public API including package documentation.
  - [X] [Instrumentation documentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#instrumentation-packages) updated.
- Examples
  - [X] `Dockerfile` file to build example application.
  - [X] `docker-compose.yml` to run example in a docker environment to demonstrate instrumentation.
