### ISSUE TITLE
Add instrumentation for github.com/go-kit/kit

### ISSUE THREAD

**Issue by sagikazarmark** [open-telemetry/opentelemetry-go-contrib#434]
Opening an issue for Go kit based on the discussion in #432
I intend to work on this one and submit a PR.

https://github.com/go-kit/kit

## Tasks

* [ ]  code complete with tests passing
* [ ]  `Dockerfile` with example app showing instrumentation (alternatively link to https://github.com/sagikazarmark/modern-go-application which serves as an example app for Go kit, showcasing OpenTelemetry as well)
* [ ]  documentation updated
* [ ]  instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

Go kit provides built-in support for OpenCensus, I'd like to use that as a template (together with existing framework integrations in this repo):

https://github.com/go-kit/kit/tree/master/tracing/opencensus

Apart from HTTP and gRPC integrations, it contains go kit specific logic (eg. business error code).

**Comment by sagikazarmark** [comment]
@MrAlias the PR is ready and has been approved by some folks. I've been rebasing it for weeks (or months?) to always use the latest version and I'd love to leave that to the automation. 🙂 

Do you know who can hit that merge button on the PR? Maybe you? 🙂
