### ISSUE TITLE
todo: adhere to the HTTP span naming semconv processing checklist

### ISSUE THREAD

**Issue by flc1125** [open-telemetry/opentelemetry-go-contrib#6375]
Based on https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6365#discussion_r1858025667, organize the following list of items that need to be processed:

- [ ] go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux
- [ ] go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin
- [ ] go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp

> If there are any omissions, please let me know.

**Reference solution:**

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6365/files

**References:**

- https://github.com/open-telemetry/opentelemetry-specification/blob/v1.20.0/specification/trace/semantic_conventions/http.md#name

**Comment by flc1125** [comment]
To avoid repetition, synchronize as follows:

I am processing this: `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin`

**Comment by dmathieu** [comment]
I wonder whether we should really remove the custom span methods.

See https://github.com/open-telemetry/opentelemetry-collector/pull/11230
As a valid use of a custom span name.

**Comment by pellared** [comment]
I think this can be split this into two issues:
1.  Change the default span naming to adhere to semantic conventions
2. Deprecate (and later remove) `SpanNameFormatter`

**Comment by flc1125** [comment]
> I think this can be split this into two issues:
> 
> 1. Change the default span naming to adhere to semantic conventions
> 2. Deprecate (and later remove) `SpanNameFormatter`
> 
> We may decide just to address the first issue if there would be a push-back to keep `SpanNameFormatter`

Good idea, I will first solve the first problem. For the second problem, I will leave it as is for now.
