### ISSUE TITLE
Add instrumentation for go-restful

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#79]
https://github.com/emicklei/go-restful

## Tasks

- [x] code complete with tests passing
- [x] `Dockerfile` with example app showing instrumentation
- [x] documentation updated
- [x] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

- https://github.com/opentracing-contrib/go-restful
- https://github.com/DataDog/dd-trace-go/tree/v1/contrib/emicklei/go-restful

**Comment by MrAlias** [comment]
Prior art for OpenTracing:

- https://github.com/opentracing-contrib/go-restful
- https://github.com/DataDog/dd-trace-go/tree/v1/contrib/emicklei/go-restful

**Comment by MrAlias** [comment]
Closed in error, still need to complete the checklist.

**Comment by evantorrie** [comment]
Instrumentation registry added in PR https://github.com/open-telemetry/opentelemetry.io/pull/213.

Note, I also added a couple of others that were missing in https://github.com/open-telemetry/opentelemetry.io/pull/211

**Comment by evantorrie** [comment]
Documentation is likely already sufficient, but gave a little more color in #121
