### ISSUE TITLE
Add Instrumentation for `gofiber/fiber`

### ISSUE THREAD

**Issue by WLun001** [open-telemetry/opentelemetry-go-contrib#843]
## Background

**Package Link**: https://github.com/gofiber/fiber

<describe how this package is commonly used>

## Proposed Solution

middlewares

### Tracing

- attributes:
  - semconv.NetAttributesFromHTTPRequest
  - semconv.EndUserAttributesFromHTTPRequest
  - semconv.HTTPServerAttributesFromHTTPRequest
  - semconv.HTTPAttributesFromHTTPStatusCode
  - semconv.SpanStatusFromHTTPStatusCode
- events:
  - Incoming HTTP request

### Prior Art

- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/github.com/gin-gonic/gin/otelgin

## Tasks

- Code complete:
  - [x] Comprehensive unit tests.
  - [x] End-to-end integration tests.
  - [x] Tests all passing.
  - [x] Instrumentation functionality verified.
- Documented
  - [x] Added to the [OpenTelemetry Registry](https://opentelemetry.io/registry/)
  - [x] README included for the module describing high-level purpose.
  - [x] Complete documentation of all public API including package documentation.
  - [x] [Instrumentation documentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/README.md#instrumentation-packages) updated.
- Examples
  - [x] `Dockerfile` file to build example application.
  - [x] `docker-compose.yml` to run example in a docker environment to demonstrate instrumentation.

**Comment by WLun001** [comment]
working on it

**Comment by MrAlias** [comment]
In accordance with the [new instrumentation policy hosting guidelines](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation#new-instrumentation) I'm closing this.
