### ISSUE TITLE
Add instrumentation for Cassandra: github.com/gocql/gocql

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-contrib#91]
https://github.com/gocql/gocql

## Tasks

- [x] code complete with tests passing
- [x] `Dockerfile` with example app showing instrumentation
- [x] documentation updated
- [x] instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)

## Prior Art

- https://github.com/DataDog/dd-trace-go/tree/v1/contrib/gocql/gocql

**Comment by reggiemcdonald** [comment]
@MrAlias could I give this a try?

**Comment by reggiemcdonald** [comment]
After a bit of research it appears that I can either: 
- Create an implementation of [`gocql.Tracer`](https://github.com/gocql/gocql/blob/c6852bb0463ade62d1234270419b7c948b45a7e1/session.go#L591-L598), which appears to be quite resource intensive with the multiple queries to the Database, but does not require the creation of a wrapper
- Create a wrapper around `gocql.Session` and avoid using the Tracer hook

Any suggestions which might be the better approach?

**Comment by Aneurysm9** [comment]
The comment on the `gocql.Tracer` type says: 

> Gathering this information might be essential for debugging and optimizing queries, but this feature should not be used on production systems with very high load.

That would lead me to believe that creating a wrapper is the better approach.  Ideally we'd be able to leave the instrumentation enabled at all times.

**Comment by reggiemcdonald** [comment]
> The comment on the `gocql.Tracer` type says:
> 
> > Gathering this information might be essential for debugging and optimizing queries, but this feature should not be used on production systems with very high load.
> 
> That would lead me to believe that creating a wrapper is the better approach. Ideally we'd be able to leave the instrumentation enabled at all times.

Perfect that's what I thought. Thanks!

**Comment by reggiemcdonald** [comment]
> https://github.com/gocql/gocql
> 
> ## Tasks
> * [x]  code complete with tests passing
> * [x]  `Dockerfile` with example app showing instrumentation
> * [x]  documentation updated
> * [x]  instrumentation added to the opentelemetry [registry](https://opentelemetry.io/registry/)
> 
> ## Prior Art
> * https://github.com/DataDog/dd-trace-go/tree/v1/contrib/gocql/gocql

All tasks completed, ready to close

**Comment by MrAlias** [comment]
Awesome :tada:! Thanks for the help @reggiemcdonald
